In [ ]:
Importing libraries

In [2]:
import numpy as np

## Creating numpy array

1) Using np.array()
2) Using np.zeros/one/empty/random()
3) Using np.arange()
4) Using np.linspace()
5) Using Identitiy
6) Using Copy()

In [5]:
# Using np.array()  --> 1 dim
arr1 = np.array([2,3,5,7,11])
arr1

array([ 2,  3,  5,  7, 11])

In [6]:
# Using np.array()  --> 2 dim
arr2 = np.array([[1,3,5,7,9],[0,2,4,6,8]])
arr2

array([[1, 3, 5, 7, 9],
       [0, 2, 4, 6, 8]])

In [7]:
# Using np.array()  --> 3 dim
arr3 = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

In [8]:
type(arr3)

numpy.ndarray

In [9]:
# Using np.zeros
arr4 = np.zeros([5,2])
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# Using np.ones
arr5 = np.ones([3,3])
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Using np.empty
arr6 = np.empty([2,6])
arr6

array([[1.10415460e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 1.03977794e-312, 2.92966904e-033],
       [7.17930486e-091, 2.36053201e+180, 8.26661920e-072,
        6.52537023e-038, 3.99910963e+252, 1.90979636e-312]])

In [12]:
# Using np.random
arr7 = np.random.rand(5)
arr7

array([0.37306624, 0.72823529, 0.63692438, 0.24393214, 0.91402169])

In [13]:
# Using np.arange
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr9 = np.arange(2,25,2)
arr9

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [15]:
# Using linspace
arr10 = np.linspace(10,20,3)
arr10

array([10., 15., 20.])

In [16]:
arr11 = np.linspace(1,30,12)
arr11

array([ 1.        ,  3.63636364,  6.27272727,  8.90909091, 11.54545455,
       14.18181818, 16.81818182, 19.45454545, 22.09090909, 24.72727273,
       27.36363636, 30.        ])

In [17]:
arr12 = np.identity(6)
arr12

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
arr12 = arr11.copy()
arr12

array([ 1.        ,  3.63636364,  6.27272727,  8.90909091, 11.54545455,
       14.18181818, 16.81818182, 19.45454545, 22.09090909, 24.72727273,
       27.36363636, 30.        ])

## Properties & Attributes

1) Shape
2) nDim
3) Size
4) Itemsize
5) Dtype
6) astype

In [19]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

In [20]:
# Shape
arr3.shape

(2, 2, 3)

In [21]:
# ndim
arr3.ndim

3

In [22]:
# Size
arr3.size

12

In [23]:
# Itemsize (size of item in memory; 4 for integer & 8 for float)
arr3.itemsize   # 4 because of integer

4

In [24]:
# dtype
arr3.dtype

dtype('int32')

In [25]:
# astype (to change datatype)
arr3 = arr3.astype('float')
arr3

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[3., 2., 1.],
        [6., 5., 4.]]])

In [26]:
arr3.dtype

dtype('float64')

## Numpy arrays vs Python list

1) Less memory
2) Faster in execution
3) Convenient

In [27]:
# Less memory
listA = list(range(100))
arrayA = np.arange(100)

In [28]:
import sys     
# Calculating total size of list
print('Size of list is', sys.getsizeof(60)*len(listA), 'bytes.')

# Calculating total size of array
print('Size of array is', arrayA.itemsize * arrayA.size, 'bytes.')

Size of list is 2800 bytes.
Size of array is 400 bytes.


In [29]:
# Faster in execution
import time

In [30]:
# Calculating total time taken by list for execution
start_time = time.time()
lista = list(range(100000000))
listb = list(range(100000000,200000000))
listc = [lista + listb for lista,listb in zip(lista,listb)]
print("Total time taken by list :", time.time() - start_time, 'seconds')

Total time taken by list : 81.68343043327332 seconds


In [31]:
# Calculating total time taken by array for execution
start_time = time.time()
arraya = np.arange(100000000)
arrayb = np.arange(100000000,200000000)
arrayc = arraya + arrayb
print("Total time taken by array :", time.time() - start_time, 'seconds')

Total time taken by array : 1.279796838760376 seconds


## Indexing and slicing array

Fetching one item --> Indexing

Fetching multiple item --> Slicing

In [34]:
arr13 = np.arange(24).reshape(6,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
# Fetching a row
arr13[2]

array([ 8,  9, 10, 11])

In [43]:
# Fetching last row
arr13[-1]

array([20, 21, 22, 23])

In [38]:
# Fetching a column
arr13[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [39]:
# Fetching a single value
arr13[1,1]

5

In [40]:
# Fetching multiples values
arr13[2:4,2:4]

array([[10, 11],
       [14, 15]])

## Iterating the array

1) Using loop
2) Using nditer function (to iterate item by item)

In [45]:
# Iterating the array using loop
for i in arr13:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [46]:
# Iterating the array using nditer function (item by item)
for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Numpy Array Basic Operations

1) Subtraction
2) Addition (vector addition)
3) Multiplication (vector multiplication)
4) Division
5) Less than 
6) Greater than
7) Square
8) Cube
9) Scalar addition
10) Scalar multiplication
11) Dot product

In [48]:
array01 = np.array([1,3,5,7,9])
array02 = np.array([2,4,6,8,10])

In [55]:
# Subtraction
array01 - array02

array([-1, -1, -1, -1, -1])

In [51]:
# Addition (vector addition)
array01 + array02

array([ 3,  7, 11, 15, 19])

In [52]:
# Multiplication (vector multiplication)
array01 * array02

array([ 2, 12, 30, 56, 90])

In [53]:
# Division
array01 / array02

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])

In [58]:
# Comparing each item of array whether it is greater than given value or not
array01 > 5

array([False, False, False,  True,  True])

In [60]:
# Comparing each item of array whether it is lesser than given value or not
array01 < 6

array([ True,  True,  True, False, False])

In [62]:
# Taking square of array
array01 ** 2

array([  1,  27, 125, 343, 729], dtype=int32)

In [63]:
# Taking cube of array
array02 ** 3

array([   8,   64,  216,  512, 1000], dtype=int32)

In [65]:
# Scalar addition
array01 + 5

array([ 6,  8, 10, 12, 14])

In [66]:
# Scalar multiplication
array02 * 3

array([ 6, 12, 18, 24, 30])

In [91]:
# Dot product of two array
array03 = np.arange(1,12,2).reshape(3,2)
array04 = np.arange(2,13,2).reshape(2,3)
array05 = array03.dot(array04)
array05

array([[ 906,  973, 1040],
       [ 960, 1031, 1102],
       [1014, 1089, 1164]])

## Numpy array unary operations

1) Min
2) Max
3) Sum

In [10]:
array06 = np.array([[2,6,9],[4,6,1],[11,4,2]])
array06

array([[ 2,  6,  9],
       [ 4,  6,  1],
       [11,  4,  2]])

In [93]:
# Minimum value in array
array06.min()

2

In [97]:
# Minimum value in array column wise
array06.min(axis=0)

array([2, 4, 1])

In [98]:
# Minimum value in array row wise
array06.min(axis=1)

array([2, 1, 2])

In [100]:
# Maximum value in array
array06.max()

11

In [101]:
# Maximum value in array column wise
array06.max(axis=0)

array([11,  6,  9])

In [102]:
# Maximum value in array row wise
array06.max(axis=1)

array([ 9,  6, 11])

In [103]:
# Sum of array
array06.sum()

45

In [105]:
# Sum of array column wise
array06.sum(axis=0)

array([17, 16, 12])

In [106]:
# Sum of array row wise
array06.sum(axis=1)

array([17, 11, 17])

## Numpy Array Universal Functions

1) Exponent
2) Square root
3) sin/cos/tan
4) Median
5) Mean
6) Average
7) Standard Deviation

In [3]:
array07 = np.arange(8).reshape(2,4)
array07

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
# Exponent
np.exp(array07)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]])

In [5]:
# Square root
np.sqrt(array07)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131]])

In [6]:
# sin function
np.sin(array07)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]])

In [7]:
# cos function
np.cos(array07)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225]])

In [8]:
#ntan function
np.tan(array07)

array([[ 0.        ,  1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619,  0.87144798]])

In [9]:
# Median
np.median(array07)

3.5

In [16]:
# Mean
np.mean(array07)

3.5

In [17]:
# Average
np.average(array07)

3.5

In [23]:
# Standard Deviation
np.std(array07)

2.29128784747792

## Reshaping numpy array

1) Ravel
2) Reshape
3) Transpose
4) Stacking
5) Splitting

In [27]:
array07

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
# Ravel (Higher dimension to one dimension)
array07.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
# Reshape (Reshape the numpy array)
array07.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [32]:
# Reshape (Reshape the numpy array)
array07.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
# Transpose ( interchanging rows into columns or columns into rows)
array07.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [35]:
array08 = array07.copy()
array08

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
# Stacking arrays horizontally
np.hstack((array07, array08))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [39]:
# Stacking array vertically
np.vstack((array07,array08))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
# Splitting the array in horizontal manner
np.hsplit(array08,4)

[array([[0],
        [4]]),
 array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]])]

In [46]:
# Splitting the array in vertical manner
np.vsplit(array08,2)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

## Fancy indexing

In [59]:
array09 = np.arange(0,36).reshape(6,6)
array09

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [49]:
# Fetching discontinuous rows
array09[[0,5]]

array([[ 0,  1,  2,  3,  4,  5],
       [30, 31, 32, 33, 34, 35]])

In [60]:
# Fetching discontinuous columns
array09[:,[1,3,5]]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

## Indexing using Boolean Array

In [62]:
arr1 = np.random.randint(low=1, high=100, size=25).reshape(5,5)
arr1

array([[39, 11, 84, 63, 60],
       [87,  7, 76, 69, 74],
       [97, 16, 98, 22, 65],
       [19, 65, 78, 79, 73],
       [52, 46, 17, 78, 19]])

In [67]:
# Filtering array for the values which are greater than 50
arr1[arr1>50]

SyntaxError: invalid syntax (1374680253.py, line 1)

In [64]:
# Filtering array for the values which are greater than 50 and are odd
arr1[(arr1>50) & (arr1 % 2 != 0)]

array([63, 87, 69, 97, 65, 65, 79, 73])

In [66]:
# Filtering array for the values which are greater than 50 and are odd and then setting them 0 
arr1[(arr1>50) & (arr1 % 2 != 0)] = 0
arr1

array([[39, 11, 84,  0, 60],
       [ 0,  7, 76,  0, 74],
       [ 0, 16, 98, 22,  0],
       [19,  0, 78,  0,  0],
       [52, 46, 17, 78, 19]])

## Some other important numpy functions

In [6]:
np.random.random()     # It gives random number each time we run.

0.666057260534201

In [14]:
np.random.seed(1)     # It will give same random number each time we run.
np.random.random()

0.417022004702574

In [16]:
np.random.uniform(12,24)   # It will give a random number within provided range

20.643893921305896

In [17]:
np.random.uniform(1,100,10)    # Third parameter is for size; in this case it will give an array of 10 values

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [18]:
np.random.randint(1,100)    # This will give integer random value instead of floating point

12

In [19]:
np.random.randint(1,100,19)    # Third parameter is for size; in this case it will give an array of 19 values

array([29, 30, 15, 51, 69, 88, 88, 95, 97, 87, 14, 10,  8, 64, 62, 23, 58,
        2,  1])

In [21]:
x = np.random.uniform(2,54,10)
x

array([48.5195465 ,  6.42229899,  4.03084873, 10.83118182, 47.66341018,
        7.11403536, 23.8975965 , 51.81025557, 29.72459482, 37.97760993])

In [23]:
np.argmax(x)    # It will give index of largest number in a array

7

In [24]:
np.argmin(x)    # It will give index of smallest number in a 

2

In [25]:
y = np.random.randint(1,30,5)
y

array([18, 12, 13, 27, 21])

In [27]:
np.where(y%2==1,-1,1)    # It actually is like this [np.where(condition,if true,if false)]

array([ 1,  1, -1, -1, -1])

In [28]:
z = np.random.randint(1,30,5)
z

array([17, 14, 20, 10, 19])

In [30]:
z = np.sort(z)    # Sorting the array
z

array([10, 14, 17, 19, 20])

In [31]:
np.percentile(z,20) 
# NumPy percentile() function in Python is used to compute the nth percentile of the array elements along the specified axis. 
# We basically use percentile in statistics which gives you a number that describes the value that a given percent of the values
# are lower than.

13.2

In [32]:
np.percentile(z,100)

20.0